global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']
    
  - job_name: 'react-client'
    static_configs:
      - targets: ['react-client:4000']
    metrics_path: '/metrics'
    scrape_interval: 15s
  
  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:8002']

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8001']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']